# Generated by Django 5.0.6 on 2024-07-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(),
        ),
    ]
