# Generated by Django 5.0.6 on 2024-07-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default='Loading...'),
        ),
    ]
